#ifndef OBJECT_TYPE_H
#define OBJECT_TYPE_H


#define OBJET_CONNECT 400
#define OBJET_DISCONNECT 401
#define OBJET_GAME_SAVE 402
#define OBJET_ASK_SAVE 403

#define OBJET_SPAWN_FOOD 410
#define OBJET_DELETE_FOOD 411

#define OBJET_SPAWN_BOB 420
#define OBJET_UPDATE_BOB 421
#define OBJET_DELETE_BOB 422

#define DELEGATE 499

#define C_COMMAND 65535

#endif 
